openapi: 3.0.3
info:
  title: Matcha Composite Service
  version: 0.1.0
  description: >
    Composite microservice that aggregates data from the User, Budget, and Ranking
    atomic microservices. Provides summary views and enforces logical foreign key
    constraints.

servers:
  - url: http://localhost:8000
    description: Local dev

paths:
  /summary/users/{user_id}:
    get:
      summary: Get matcha summary for a user
      description: >
        Fetches user profile, recent orders, and recent ratings for the given user.
        The composite calls the User, Budget, and Ranking services in parallel and
        aggregates the results.
      operationId: getUserSummary
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
          description: Maximum number of recent orders and ratings to include
      responses:
        '200':
          description: Summary for the specified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSummary'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /summary/users/{user_id}/orders:
    post:
      summary: Create an order for a user with FK validation
      description: >
        Validates that the user exists in the User Service, then forwards the
        request to the Budget Service to create an order associated with that user.
        Demonstrates logical foreign key enforcement in the composite microservice.
      operationId: createOrderForUser
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the user placing the order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Emily
        email:
          type: string
          example: emily@example.com
        favorite_cafe:
          type: string
          nullable: true
          example: Matchaful
        favorite_powder:
          type: string
          nullable: true
          example: Ippodo

    Order:
      type: object
      properties:
        id:
          type: integer
          example: 10
        user_id:
          type: integer
          example: 1
        drink_name:
          type: string
          example: Iced Matcha Latte
        type:
          type: string
          enum: [cafe, home]
        cafe_name:
          type: string
          nullable: true
          example: Matchaful
        price:
          type: number
          format: float
          example: 6.5
        order_time:
          type: string
          format: date-time
          example: 2025-03-01T10:00:00Z

    Rating:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        order_id:
          type: integer
        score:
          type: integer
          minimum: 1
          maximum: 5
        notes:
          type: string
          nullable: true

    UserSummary:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        recentOrders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        recentRatings:
          type: array
          items:
            $ref: '#/components/schemas/Rating'
        stats:
          type: object
          properties:
            totalSpent:
              type: number
              format: float
              nullable: true
              example: 42.5
            averageRating:
              type: number
              format: float
              nullable: true
              example: 4.6
            numOrders:
              type: integer
              example: 7
            numRatings:
              type: integer
              example: 5

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: User not found
